import type { JSX } from "preact";
import type { AppSnapshot, MatrixStore } from "../../store";
export function ReportDialog({ snapshot, store }: { readonly snapshot: AppSnapshot; readonly store: MatrixStore }): JSX.Element { if (!snapshot.reportOpen) return <></>; const options = snapshot.reportOptions; const toggle = (key: keyof typeof options, value: boolean | string): void => store.setReportOptions({ ...options, [key]: value }); const checks: readonly [keyof typeof options,string][] = [["includeSummary","Summary"],["includeFingerprint","Device fingerprint"],["includeGatt","GATT"],["includeDriverResolution","Driver resolution"],["includeCapabilities","Capabilities / support status"],["includeDiagnosticRuns","Diagnostic runs"],["includeTransactions","Transactions"],["includeRawPacketHex","Raw packet hex"],["includeEvidence","Evidence / unknowns / rejected hypotheses"],["includeObservations","Observations"],["includeTextContent","User text content in compiler evidence"],["includeIdentifiers","Browser/device identifiers"],["includeRawTrace","Full raw event trace"]]; const filename = `matrixsmith-report-${new Date().toISOString().slice(0,10)}`; return <div class="dialog-backdrop" onClick={() => store.closeReport()}><section class="report-dialog" role="dialog" aria-modal="true" aria-labelledby="report-title" onClick={(event) => event.stopPropagation()}><header><div><p class="eyebrow">SAFE TO SHARE BY DEFAULT</p><h1 id="report-title">{snapshot.reportKind === "investigation" ? "Investigation report" : snapshot.reportKind === "forensic" ? "Forensic report" : "Low-level device report"}</h1></div><button class="close" aria-label="Close report" onClick={() => store.closeReport()}>×</button></header><div class="report-layout"><form class="report-options"><fieldset class="report-kinds"><legend>Report</legend>
  {/* An active investigation is what the user is doing, so its report leads.
      The low-level device report stays reachable but is labelled for what it
      is rather than presented as the obvious artifact to share. */}
  {snapshot.investigationReportAvailable && <label><input type="radio" name="report-kind" checked={snapshot.reportKind === "investigation"} onChange={() => store.setReportKind("investigation")}/><span>Investigation — what was tested and concluded</span></label>}
  <label><input type="radio" name="report-kind" checked={snapshot.reportKind === "forensic"} onChange={() => store.setReportKind("forensic")}/><span>Forensic — every transaction and packet</span></label>
  <label><input type="radio" name="report-kind" checked={snapshot.reportKind === "device"} onChange={() => store.setReportKind("device")}/><span>Low-level device report <small>legacy</small></span></label>
</fieldset><label><strong>Goal / question</strong><textarea rows={4} placeholder="What should a reviewer help determine?" value={options.goal} onInput={(event) => toggle("goal", (event.currentTarget as HTMLTextAreaElement).value)}/></label><fieldset class={snapshot.reportKind === "device" ? "" : "muted-options"}><legend>Include{snapshot.reportKind !== "device" && <small> — applies to the low-level report</small>}</legend>{checks.map(([key,label]) => <label class={key === "includeIdentifiers" || key === "includeRawTrace" ? "sensitive" : ""}><input type="checkbox" checked={Boolean(options[key])} onChange={(event) => toggle(key, (event.currentTarget as HTMLInputElement).checked)}/><span>{label}</span>{key === "includeIdentifiers" && <small>May identify this browser/device</small>}</label>)}</fieldset>{options.includeIdentifiers && <p class="notice warning">Identifying information is included by your choice. Review the preview before sharing.</p>}</form><div class="report-preview"><div class="preview-title"><strong>Markdown preview</strong><span>{snapshot.reportMarkdown.length.toLocaleString()} characters</span></div><pre>{snapshot.reportMarkdown}</pre></div></div><footer><button class="primary" onClick={() => void store.copy(snapshot.reportMarkdown)}>Copy Markdown</button><button class="secondary" onClick={() => store.download(`${filename}.md`, snapshot.reportMarkdown, "text/markdown")}>Download .md</button><button class="secondary" onClick={() => store.download(`${filename}.json`, store.exportBundle(), "application/json")}>Download diagnostic JSON</button></footer></section></div>; }
